### ISSUE TITLE
Failed to connect EKS cluster

### ISSUE THREAD

**Issue by tht-activeviam** [microbean/microbean-helm#202]
I have an EKS cluster on AWS. I generate kubeconfig file from that cluster and setup my kubectl. kubectl commands are working in terminal. 
I setup microbean-helm(2.8.2.1.1.1) with `new DefaultKuernetesClient()` which will pickup the same kubeconfig by default.  It failed with below error
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://<my cluster address>.ap-southeast-1.eks.amazonaws.com/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm,name%3Dtiller. Message: Forbidden! User eks-dist-cube-test-user doesn't have permission. pods is forbidden: User "system:anonymous" cannot list resource "pods" in API group "" in the namespace "kube-system".
```
Here is user setting in kubeconfig:
```yml
users:
- name: eks-dist-cube-test-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "EKS-cXUfbePY5ujw"
```
